const imageConfig = {
    'destacadas': [], // Se llenará dinámicamente
    'bikini': [
        { name: 'Bikini 1', url: 'images/bikini/bikini (1).png' },
        { name: 'Bikini 2', url: 'images/bikini/bikini (2).png' },
        { name: 'Bikini 3', url: 'images/bikini/bikini (3).png' },
        { name: 'Bikini 4', url: 'images/bikini/bikini (4).png' },
        { name: 'Bikini 5', url: 'images/bikini/bikini (5).png' },
        { name: 'Bikini 6', url: 'images/bikini/bikini (6).png' },
        { name: 'Bikini 7', url: 'images/bikini/bikini (7).png' },
        { name: 'Bikini 8', url: 'images/bikini/bikini (8).png' },
        { name: 'Bikini 9', url: 'images/bikini/bikini (9).png' },
        { name: 'Bikini 10', url: 'images/bikini/bikini (10).png' },
        { name: 'Bikini 11', url: 'images/bikini/bikini (11).png' },
        { name: 'Bikini 12', url: 'images/bikini/bikini (12).png' },
        { name: 'Bikini 13', url: 'images/bikini/bikini (13).png' },
        { name: 'Bikini 14', url: 'images/bikini/bikini (14).png' },
        { name: 'Bikini 15', url: 'images/bikini/bikini (15).png' },
        { name: 'Bikini 16', url: 'images/bikini/bikini (16).png' },
        { name: 'Bikini 17', url: 'images/bikini/bikini (17).png' },
        { name: 'Bikini 18', url: 'images/bikini/bikini (18).png' },
        { name: 'Bikini 19', url: 'images/bikini/bikini (19).png' },
        { name: 'Bikini 20', url: 'images/bikini/bikini (20).png' }
      
    ],
    'cencura': [
        { name: 'Censurada 1', url: 'images/cencura/cencura (1).png' },
        { name: 'Censurada 2', url: 'images/cencura/cencura (2).png' },
        { name: 'Censurada 3', url: 'images/cencura/cencura (3).png' },
        { name: 'Censurada 4', url: 'images/cencura/cencura (4).png' },
        { name: 'Censurada 5', url: 'images/cencura/cencura (5).png' },
        { name: 'Censurada 6', url: 'images/cencura/cencura (6).png' },
        { name: 'Censurada 7', url: 'images/cencura/cencura (7).png' },
        { name: 'Censurada 8', url: 'images/cencura/cencura (8).png' },
        { name: 'Censurada 9', url: 'images/cencura/cencura (9).png' },
        { name: 'Censurada 10', url: 'images/cencura/cencura (10).png' },
        { name: 'Censurada 11', url: 'images/cencura/cencura (11).png' },
        { name: 'Censurada 12', url: 'images/cencura/cencura (12).png' },
        { name: 'Censurada 13', url: 'images/cencura/cencura (13).png' },
        { name: 'Censurada 14', url: 'images/cencura/cencura (14).png' },
        { name: 'Censurada 15', url: 'images/cencura/cencura (15).png' },
        { name: 'Censurada 16', url: 'images/cencura/cencura (16).png' },
        { name: 'Censurada 17', url: 'images/cencura/cencura (17).png' },
        { name: 'Censurada 18', url: 'images/cencura/cencura (18).png' },
        { name: 'Censurada 19', url: 'images/cencura/cencura (19).png' },
        { name: 'Censurada 20', url: 'images/cencura/cencura (20).png' },   
        { name: 'Censurada 21', url: 'images/cencura/cencura (21).png' },
        { name: 'Censurada 22', url: 'images/cencura/cencura (22).png' },
        { name: 'Censurada 23', url: 'images/cencura/cencura (23).png' },
        { name: 'Censurada 24', url: 'images/cencura/cencura (24).png' },
        { name: 'Censurada 25', url: 'images/cencura/cencura (25).png' },
        { name: 'Censurada 26', url: 'images/cencura/cencura (26).png' },
        { name: 'Censurada 27', url: 'images/cencura/cencura (27).png' },
        { name: 'Censurada 28', url: 'images/cencura/cencura (28).png' },
        { name: 'Censurada 29', url: 'images/cencura/cencura (29).png' },
        { name: 'Censurada 30', url: 'images/cencura/cencura (30).png' },
        { name: 'Censurada 31', url: 'images/cencura/cencura (31).png' },
        { name: 'Censurada 32', url: 'images/cencura/cencura (32).png' },
        { name: 'Censurada 33', url: 'images/cencura/cencura (33).png' },
        { name: 'Censurada 34', url: 'images/cencura/cencura (34).png' },
        { name: 'Censurada 35', url: 'images/cencura/cencura (35).png' },
        { name: 'Censurada 36', url: 'images/cencura/cencura (36).png' },
        { name: 'Censurada 37', url: 'images/cencura/cencura (37).png' },
        { name: 'Censurada 38', url: 'images/cencura/cencura (38).png' },
        { name: 'Censurada 39', url: 'images/cencura/cencura (39).png' },
        { name: 'Censurada 40', url: 'images/cencura/cencura (40).png' },
        { name: 'Censurada 41', url: 'images/cencura/cencura (41).png' },
        { name: 'Censurada 42', url: 'images/cencura/cencura (42).png' },
        { name: 'Censurada 43', url: 'images/cencura/cencura (43).png' },
        { name: 'Censurada 44', url: 'images/cencura/cencura (44).png' },
        { name: 'Censurada 45', url: 'images/cencura/cencura (45).png' },
        { name: 'Censurada 46', url: 'images/cencura/cencura (46).png' },
        { name: 'Censurada 47', url: 'images/cencura/cencura (47).png' },
        { name: 'Censurada 48', url: 'images/cencura/cencura (48).png' },
        { name: 'Censurada 49', url: 'images/cencura/cencura (49).png' },
        { name: 'Censurada 50', url: 'images/cencura/cencura (50).png' },
        { name: 'Censurada 51', url: 'images/cencura/cencura (51).png' },
        { name: 'Censurada 52', url: 'images/cencura/cencura (52).png' },
        { name: 'Censurada 53', url: 'images/cencura/cencura (53).png' },
        { name: 'Censurada 54', url: 'images/cencura/cencura (54).png' },
        { name: 'Censurada 55', url: 'images/cencura/cencura (55).png' },
        { name: 'Censurada 56', url: 'images/cencura/cencura (56).png' },
        { name: 'Censurada 57', url: 'images/cencura/cencura (57).png' },
        { name: 'Censurada 58', url: 'images/cencura/cencura (58).png' },
        { name: 'Censurada 59', url: 'images/cencura/cencura (59).png' },
        { name: 'Censurada 60', url: 'images/cencura/cencura (60).png' },
        { name: 'Censurada 61', url: 'images/cencura/cencura (61).png' },
        { name: 'Censurada 62', url: 'images/cencura/cencura (62).png' },
        { name: 'Censurada 63', url: 'images/cencura/cencura (63).png' },
        { name: 'Censurada 64', url: 'images/cencura/cencura (64).png' },
        { name: 'Censurada 65', url: 'images/cencura/cencura (65).png' },
        { name: 'Censurada 66', url: 'images/cencura/cencura (66).png' },
        { name: 'Censurada 67', url: 'images/cencura/cencura (67).png' },
        { name: 'Censurada 68', url: 'images/cencura/cencura (68).png' },
        { name: 'Censurada 69', url: 'images/cencura/cencura (69).png' },
        { name: 'Censurada 70', url: 'images/cencura/cencura (70).png' },
        { name: 'Censurada 71', url: 'images/cencura/cencura (71).png' },
        { name: 'Censurada 72', url: 'images/cencura/cencura (72).png' },
        { name: 'Censurada 73', url: 'images/cencura/cencura (73).png' },
        { name: 'Censurada 74', url: 'images/cencura/cencura (74).png' },
        { name: 'Censurada 75', url: 'images/cencura/cencura (75).png' },
        { name: 'Censurada 76', url: 'images/cencura/cencura (76).png' },
        { name: 'Censurada 77', url: 'images/cencura/cencura (77).png' },
        { name: 'Censurada 78', url: 'images/cencura/cencura (78).png' },
        { name: 'Censurada 79', url: 'images/cencura/cencura (79).png' },
        { name: 'Censurada 80', url: 'images/cencura/cencura (80).png' },
        { name: 'Censurada 81', url: 'images/cencura/cencura (81).png' },
        { name: 'Censurada 82', url: 'images/cencura/cencura (82).png' },
        { name: 'Censurada 83', url: 'images/cencura/cencura (83).png' },
        { name: 'Censurada 84', url: 'images/cencura/cencura (84).png' }

    ],
    'centauro': [
        { name: 'Centauro 1', url: 'images/centauro/centauro (1).png' },
        { name: 'Centauro 2', url: 'images/centauro/centauro (2).png' },
        { name: 'Centauro 3', url: 'images/centauro/centauro (3).png' },
        { name: 'Centauro 4', url: 'images/centauro/centauro (4).png' },
        { name: 'Centauro 5', url: 'images/centauro/centauro (5).png' },
        { name: 'Centauro 6', url: 'images/centauro/centauro (6).png' },
        { name: 'Centauro 7', url: 'images/centauro/centauro (7).png' },
        { name: 'Centauro 8', url: 'images/centauro/centauro (8).png' },
        { name: 'Centauro 9', url: 'images/centauro/centauro (9).png' },
        { name: 'Centauro 10', url: 'images/centauro/centauro (10).png' }

    ],
    'chibi': [
        { name: 'Chibi 1', url: 'images/chibi/chibi (1).png' },
        { name: 'Chibi 2', url: 'images/chibi/chibi (2).png' },
        { name: 'Chibi 3', url: 'images/chibi/chibi (3).png' },
        { name: 'Chibi 4', url: 'images/chibi/chibi (4).png' },
        { name: 'Chibi 5', url: 'images/chibi/chibi (5).png' },
        { name: 'Chibi 6', url: 'images/chibi/chibi (6).png' },
        { name: 'Chibi 7', url: 'images/chibi/chibi (7).png' },
        { name: 'Chibi 8', url: 'images/chibi/chibi (8).png' },
        { name: 'Chibi 9', url: 'images/chibi/chibi (9).png' },
        { name: 'Chibi 10', url: 'images/chibi/chibi (10).png' },
        { name: 'Chibi 11', url: 'images/chibi/chibi (11).png' },
        { name: 'Chibi 12', url: 'images/chibi/chibi (12).png' },
        { name: 'Chibi 13', url: 'images/chibi/chibi (13).png' },
        { name: 'Chibi 14', url: 'images/chibi/chibi (14).png' },
        { name: 'Chibi 15', url: 'images/chibi/chibi (15).png' },
        { name: 'Chibi 16', url: 'images/chibi/chibi (16).png' },
        { name: 'Chibi 17', url: 'images/chibi/chibi (17).png' },
        { name: 'Chibi 18', url: 'images/chibi/chibi (18).png' },
        { name: 'Chibi 19', url: 'images/chibi/chibi (19).png' },
        { name: 'Chibi 20', url: 'images/chibi/chibi (20).png' },
        { name: 'Chibi 21', url: 'images/chibi/chibi (21).png' },
        { name: 'Chibi 22', url: 'images/chibi/chibi (22).png' },
        { name: 'Chibi 23', url: 'images/chibi/chibi (23).png' },
        { name: 'Chibi 24', url: 'images/chibi/chibi (24).png' },
        { name: 'Chibi 25', url: 'images/chibi/chibi (25).png' },
        { name: 'Chibi 26', url: 'images/chibi/chibi (26).png' },

    ],
    'desgarada': [
        { name: 'desgarada 1', url: 'images/desgarada/desgarada (1).png' },
        { name: 'desgarada 2', url: 'images/desgarada/desgarada (2).png' },
        { name: 'desgarada 3', url: 'images/desgarada/desgarada (3).png' },
        { name: 'desgarada 4', url: 'images/desgarada/desgarada (4).png' },
        { name: 'desgarada 5', url: 'images/desgarada/desgarada (5).png' },
        { name: 'desgarada 6', url: 'images/desgarada/desgarada (6).png' }

    ],
    'furry': [
        { name: 'furry 1', url: 'images/furry/furry (1).png' },
        { name: 'furry 2', url: 'images/furry/furry (2).png' },
        { name: 'furry 3', url: 'images/furry/furry (3).png' },
        { name: 'furry 4', url: 'images/furry/furry (4).png' },
        { name: 'furry 5', url: 'images/furry/furry (5).png' }

    ],
    'gotica': [
        { name: 'Gótica 1', url: 'images/gotica/gotica (1).png' },
        { name: 'Gótica 2', url: 'images/gotica/gotica (2).png' },
        { name: 'Gótica 3', url: 'images/gotica/gotica (3).png' },
        { name: 'Gótica 4', url: 'images/gotica/gotica (4).png' },
        { name: 'Gótica 5', url: 'images/gotica/gotica (5).png' },
        { name: 'Gótica 6', url: 'images/gotica/gotica (6).png' },
        { name: 'Gótica 7', url: 'images/gotica/gotica (7).png' },
        { name: 'Gótica 8', url: 'images/gotica/gotica (8).png' },
        { name: 'Gótica 9', url: 'images/gotica/gotica (9).png' },
        { name: 'Gótica 10', url: 'images/gotica/gotica (10).png' },
        { name: 'Gótica 11', url: 'images/gotica/gotica (11).png' },
        { name: 'Gótica 12', url: 'images/gotica/gotica (12).png' },
        { name: 'Gótica 13', url: 'images/gotica/gotica (13).png' },
        { name: 'Gótica 14', url: 'images/gotica/gotica (14).png' },
        { name: 'Gótica 15', url: 'images/gotica/gotica (15).png' },
        { name: 'Gótica 16', url: 'images/gotica/gotica (16).png' },
        { name: 'Gótica 17', url: 'images/gotica/gotica (17).png' },
        { name: 'Gótica 18', url: 'images/gotica/gotica (18).png' },
        { name: 'Gótica 19', url: 'images/gotica/gotica (19).png' },
        { name: 'Gótica 20', url: 'images/gotica/gotica (20).png' },
        { name: 'Gótica 21', url: 'images/gotica/gotica (21).png' },
        { name: 'Gótica 22', url: 'images/gotica/gotica (22).png' },
        { name: 'Gótica 23', url: 'images/gotica/gotica (23).png' },
        { name: 'Gótica 24', url: 'images/gotica/gotica (24).png' },
        { name: 'Gótica 25', url: 'images/gotica/gotica (25).png' },
        { name: 'Gótica 26', url: 'images/gotica/gotica (26).png' }

    ],
    'milf': [
        { name: 'Milf 1', url: 'images/milf/milf (1).png' },
        { name: 'Milf 2', url: 'images/milf/milf (2).png' },
        { name: 'Milf 3', url: 'images/milf/milf (3).png' },
        { name: 'Milf 4', url: 'images/milf/milf (4).png' },
        { name: 'Milf 5', url: 'images/milf/milf (5).png' },
        { name: 'Milf 6', url: 'images/milf/milf (6).png' },
        { name: 'Milf 7', url: 'images/milf/milf (7).png' },
        { name: 'Milf 8', url: 'images/milf/milf (8).png' },
        { name: 'Milf 9', url: 'images/milf/milf (9).png' },
        { name: 'Milf 10', url: 'images/milf/milf (10).png' },
        { name: 'Milf 11', url: 'images/milf/milf (11).png' },
        { name: 'Milf 12', url: 'images/milf/milf (12).png' },
        { name: 'Milf 13', url: 'images/milf/milf (13).png' },
        { name: 'Milf 14', url: 'images/milf/milf (14).png' },
        { name: 'Milf 15', url: 'images/milf/milf (15).png' },
        { name: 'Milf 16', url: 'images/milf/milf (16).png' },
        { name: 'Milf 17', url: 'images/milf/milf (17).png' },
        { name: 'Milf 18', url: 'images/milf/milf (18).png' },
        { name: 'Milf 19', url: 'images/milf/milf (19).png' },
        { name: 'Milf 20', url: 'images/milf/milf (20).png' },
        { name: 'Milf 21', url: 'images/milf/milf (21).png' },
        { name: 'Milf 22', url: 'images/milf/milf (22).png' },
        { name: 'Milf 23', url: 'images/milf/milf (23).png' },
        { name: 'Milf 24', url: 'images/milf/milf (24).png' },
        { name: 'Milf 25', url: 'images/milf/milf (25).png' },
        { name: 'Milf 26', url: 'images/milf/milf (26).png' },
        { name: 'Milf 27', url: 'images/milf/milf (27).png' },
        { name: 'Milf 28', url: 'images/milf/milf (28).png' },
        { name: 'Milf 29', url: 'images/milf/milf (29).png' },
        { name: 'Milf 30', url: 'images/milf/milf (30).png' },
        { name: 'Milf 31', url: 'images/milf/milf (31).png' },
        { name: 'Milf 32', url: 'images/milf/milf (32).png' },
        { name: 'Milf 33', url: 'images/milf/milf (33).png' },
        { name: 'Milf 34', url: 'images/milf/milf (34).png' },
        { name: 'Milf 35', url: 'images/milf/milf (35).png' },
        { name: 'Milf 36', url: 'images/milf/milf (36).png' },
        { name: 'Milf 37', url: 'images/milf/milf (37).png' },
        { name: 'Milf 38', url: 'images/milf/milf (38).png' },
        { name: 'Milf 39', url: 'images/milf/milf (39).png' }

    ],
    'morena': [
        { name: 'Morena 1', url: 'images/morena/morena (1).png' },
        { name: 'Morena 2', url: 'images/morena/morena (2).png' }

    ],
    'terror': [
        { name: 'terror 1', url: 'images/terror/terror (1).png' },
        { name: 'terror 2', url: 'images/terror/terror (2).png' },
        { name: 'terror 3', url: 'images/terror/terror (3).png' },
        { name: 'terror 4', url: 'images/terror/terror (4).png' },
        { name: 'terror 5', url: 'images/terror/terror (5).png' },
        { name: 'terror 6', url: 'images/terror/terror (6).png' }

    ],
    'trabajo': [
        { name: 'trabajo 1', url: 'images/trabajo/trabajo (1).png' },
        { name: 'trabajo 2', url: 'images/trabajo/trabajo (2).png' },
        { name: 'trabajo 3', url: 'images/trabajo/trabajo (3).png' },
        { name: 'trabajo 4', url: 'images/trabajo/trabajo (4).png' },
        { name: 'trabajo 5', url: 'images/trabajo/trabajo (5).png' },
        { name: 'trabajo 6', url: 'images/trabajo/trabajo (6).png' },
        { name: 'trabajo 7', url: 'images/trabajo/trabajo (7).png' },
        { name: 'trabajo 8', url: 'images/trabajo/trabajo (8).png' },
        { name: 'trabajo 9', url: 'images/trabajo/trabajo (9).png' },
        { name: 'trabajo 10', url: 'images/trabajo/trabajo (10).png' },
        { name: 'trabajo 11', url: 'images/trabajo/trabajo (11).png' },
        { name: 'trabajo 12', url: 'images/trabajo/trabajo (12).png' },
        { name: 'trabajo 13', url: 'images/trabajo/trabajo (13).png' },
        { name: 'trabajo 14', url: 'images/trabajo/trabajo (14).png' },
        { name: 'trabajo 15', url: 'images/trabajo/trabajo (15).png' },
        { name: 'trabajo 16', url: 'images/trabajo/trabajo (16).png' },
        { name: 'trabajo 17', url: 'images/trabajo/trabajo (17).png' },
        { name: 'trabajo 18', url: 'images/trabajo/trabajo (18).png' },
        { name: 'trabajo 19', url: 'images/trabajo/trabajo (19).png' },
        { name: 'trabajo 20', url: 'images/trabajo/trabajo (20).png' },
        { name: 'trabajo 21', url: 'images/trabajo/trabajo (21).png' },
        { name: 'trabajo 22', url: 'images/trabajo/trabajo (22).png' },
        { name: 'trabajo 23', url: 'images/trabajo/trabajo (23).png' },
        { name: 'trabajo 24', url: 'images/trabajo/trabajo (24).png' },
        { name: 'trabajo 25', url: 'images/trabajo/trabajo (25).png' },
        { name: 'trabajo 26', url: 'images/trabajo/trabajo (26).png' },
        { name: 'trabajo 27', url: 'images/trabajo/trabajo (27).png' },
        { name: 'trabajo 28', url: 'images/trabajo/trabajo (28).png' },
        { name: 'trabajo 29', url: 'images/trabajo/trabajo (29).png' },
        { name: 'trabajo 30', url: 'images/trabajo/trabajo (30).png' },
        { name: 'trabajo 31', url: 'images/trabajo/trabajo (31).png' },
        { name: 'trabajo 32', url: 'images/trabajo/trabajo (32).png' },
        { name: 'trabajo 33', url: 'images/trabajo/trabajo (33).png' },
        { name: 'trabajo 34', url: 'images/trabajo/trabajo (34).png' },
        { name: 'trabajo 35', url: 'images/trabajo/trabajo (35).png' },
        { name: 'trabajo 36', url: 'images/trabajo/trabajo (36).png' },
        { name: 'trabajo 37', url: 'images/trabajo/trabajo (37).png' },
        { name: 'trabajo 38', url: 'images/trabajo/trabajo (38).png' },
        { name: 'trabajo 39', url: 'images/trabajo/trabajo (39).png' },
        { name: 'trabajo 40', url: 'images/trabajo/trabajo (40).png' },
        { name: 'trabajo 41', url: 'images/trabajo/trabajo (41).png' },
        { name: 'trabajo 42', url: 'images/trabajo/trabajo (42).png' },
        { name: 'trabajo 43', url: 'images/trabajo/trabajo (43).png' },
        { name: 'trabajo 44', url: 'images/trabajo/trabajo (44).png' },
        { name: 'trabajo 45', url: 'images/trabajo/trabajo (45).png' },
        { name: 'trabajo 46', url: 'images/trabajo/trabajo (46).png' },
        { name: 'trabajo 47', url: 'images/trabajo/trabajo (47).png' },
        { name: 'trabajo 48', url: 'images/trabajo/trabajo (48).png' },
        { name: 'trabajo 49', url: 'images/trabajo/trabajo (49).png' },
        { name: 'trabajo 50', url: 'images/trabajo/trabajo (50).png' }

    ],
    'vampira': [
        { name: 'Vampira 1', url: 'images/vampira/vampira (1).png' },
        { name: 'Vampira 2', url: 'images/vampira/vampira (2).png' },
        { name: 'Vampira 3', url: 'images/vampira/vampira (3).png' },
        { name: 'Vampira 4', url: 'images/vampira/vampira (4).png' },
        { name: 'Vampira 5', url: 'images/vampira/vampira (5).png' },
        { name: 'Vampira 6', url: 'images/vampira/vampira (6).png' },
        { name: 'Vampira 7', url: 'images/vampira/vampira (7).png' },
        { name: 'Vampira 8', url: 'images/vampira/vampira (8).png' },
        { name: 'Vampira 9', url: 'images/vampira/vampira (9).png' },
        { name: 'Vampira 10', url: 'images/vampira/vampira (10).png' }

    ],
    'vanilla': [
        { name: 'Vanilla 1', url: 'images/vanilla/vanilla (1).png' },
        { name: 'Vanilla 2', url: 'images/vanilla/vanilla (2).png' },
        { name: 'Vanilla 3', url: 'images/vanilla/vanilla (3).png' },
        { name: 'Vanilla 4', url: 'images/vanilla/vanilla (4).png' },
        { name: 'Vanilla 5', url: 'images/vanilla/vanilla (5).png' },
        { name: 'Vanilla 6', url: 'images/vanilla/vanilla (6).png' },
        { name: 'Vanilla 7', url: 'images/vanilla/vanilla (7).png' },
        { name: 'Vanilla 8', url: 'images/vanilla/vanilla (8).png' },
        { name: 'Vanilla 9', url: 'images/vanilla/vanilla (9).png' },
        { name: 'Vanilla 10', url: 'images/vanilla/vanilla (10).png' },
        { name: 'Vanilla 11', url: 'images/vanilla/vanilla (11).png' },
        { name: 'Vanilla 12', url: 'images/vanilla/vanilla (12).png' },
        { name: 'Vanilla 13', url: 'images/vanilla/vanilla (13).png' },
        { name: 'Vanilla 14', url: 'images/vanilla/vanilla (14).png' },
        { name: 'Vanilla 15', url: 'images/vanilla/vanilla (15).png' },
        { name: 'Vanilla 16', url: 'images/vanilla/vanilla (16).png' },
        { name: 'Vanilla 17', url: 'images/vanilla/vanilla (17).png' },
        { name: 'Vanilla 18', url: 'images/vanilla/vanilla (18).png' },
        { name: 'Vanilla 19', url: 'images/vanilla/vanilla (19).png' },
        { name: 'Vanilla 20', url: 'images/vanilla/vanilla (20).png' },
        { name: 'Vanilla 21', url: 'images/vanilla/vanilla (21).png' },
        { name: 'Vanilla 22', url: 'images/vanilla/vanilla (22).png' },
        { name: 'Vanilla 23', url: 'images/vanilla/vanilla (23).png' },
        { name: 'Vanilla 24', url: 'images/vanilla/vanilla (24).png' },
        { name: 'Vanilla 25', url: 'images/vanilla/vanilla (25).png' },
        { name: 'Vanilla 26', url: 'images/vanilla/vanilla (26).png' },
        { name: 'Vanilla 27', url: 'images/vanilla/vanilla (27).png' },
        { name: 'Vanilla 28', url: 'images/vanilla/vanilla (28).png' },
        { name: 'Vanilla 29', url: 'images/vanilla/vanilla (29).png' },
        { name: 'Vanilla 30', url: 'images/vanilla/vanilla (30).png' },
        { name: 'Vanilla 31', url: 'images/vanilla/vanilla (31).png' },
        { name: 'Vanilla 32', url: 'images/vanilla/vanilla (32).png' },
        { name: 'Vanilla 33', url: 'images/vanilla/vanilla (33).png' },
        { name: 'Vanilla 34', url: 'images/vanilla/vanilla (34).png' },
        { name: 'Vanilla 35', url: 'images/vanilla/vanilla (35).png' },
        { name: 'Vanilla 36', url: 'images/vanilla/vanilla (36).png' },
        { name: 'Vanilla 37', url: 'images/vanilla/vanilla (37).png' },
        { name: 'Vanilla 38', url: 'images/vanilla/vanilla (38).png' },
        { name: 'Vanilla 39', url: 'images/vanilla/vanilla (39).png' },
        { name: 'Vanilla 40', url: 'images/vanilla/vanilla (40).png' },
        { name: 'Vanilla 41', url: 'images/vanilla/vanilla (41).png' },
        { name: 'Vanilla 42', url: 'images/vanilla/vanilla (42).png' },
        { name: 'Vanilla 43', url: 'images/vanilla/vanilla (43).png' },
        { name: 'Vanilla 44', url: 'images/vanilla/vanilla (44).png' },
        { name: 'Vanilla 45', url: 'images/vanilla/vanilla (45).png' },
        { name: 'Vanilla 46', url: 'images/vanilla/vanilla (46).png' },
        { name: 'Vanilla 47', url: 'images/vanilla/vanilla (47).png' },
        { name: 'Vanilla 48', url: 'images/vanilla/vanilla (48).png' },
        { name: 'Vanilla 49', url: 'images/vanilla/vanilla (49).png' },
        { name: 'Vanilla 50', url: 'images/vanilla/vanilla (50).png' },
        { name: 'Vanilla 51', url: 'images/vanilla/vanilla (51).png' },
        { name: 'Vanilla 52', url: 'images/vanilla/vanilla (52).png' },
        { name: 'Vanilla 53', url: 'images/vanilla/vanilla (53).png' },
        { name: 'Vanilla 54', url: 'images/vanilla/vanilla (54).png' },
        { name: 'Vanilla 55', url: 'images/vanilla/vanilla (55).png' },
        { name: 'Vanilla 56', url: 'images/vanilla/vanilla (56).png' },
        { name: 'Vanilla 57', url: 'images/vanilla/vanilla (57).png' },
        { name: 'Vanilla 58', url: 'images/vanilla/vanilla (58).png' },
        { name: 'Vanilla 59', url: 'images/vanilla/vanilla (59).png' },
        { name: 'Vanilla 60', url: 'images/vanilla/vanilla (60).png' },
        { name: 'Vanilla 61', url: 'images/vanilla/vanilla (61).png' },
        { name: 'Vanilla 62', url: 'images/vanilla/vanilla (62).png' },
        { name: 'Vanilla 63', url: 'images/vanilla/vanilla (63).png' },
        { name: 'Vanilla 64', url: 'images/vanilla/vanilla (64).png' }     

    ],
    'vestido': [
        { name: 'vestido 1', url: 'images/vestido/vestido (1).png' },
        { name: 'vestido 2', url: 'images/vestido/vestido (2).png' },
        { name: 'vestido 3', url: 'images/vestido/vestido (3).png' },
        { name: 'vestido 4', url: 'images/vestido/vestido (4).png' },
        { name: 'vestido 5', url: 'images/vestido/vestido (5).png' },
        { name: 'vestido 6', url: 'images/vestido/vestido (6).png' },
        { name: 'vestido 7', url: 'images/vestido/vestido (7).png' },
        { name: 'vestido 8', url: 'images/vestido/vestido (8).png' },
        { name: 'vestido 9', url: 'images/vestido/vestido (9).png' },
        { name: 'vestido 10', url: 'images/vestido/vestido (10).png' },

    ],
    'cliks': [
        { name: 'Clik 1', url: 'videos/cliks/clik (1).mp4' },
        { name: 'Clik 2', url: 'videos/cliks/clik (2).mp4' },
        { name: 'Clik 3', url: 'videos/cliks/clik (3).mp4' },
        { name: 'Clik 4', url: 'videos/cliks/clik (4).mp4' },
        { name: 'Clik 5', url: 'videos/cliks/clik (5).mp4' }
    ],
    'cliks18': [
        { name: 'Clik +18 1', url: 'videos/cliks_+18/clik_+18 (1).mp4' },
        { name: 'Clik +18 2', url: 'videos/cliks_+18/clik_+18 (2).mp4' },
        { name: 'Clik +18 3', url: 'videos/cliks_+18/clik_+18 (3).mp4' },
        { name: 'Clik +18 4', url: 'videos/cliks_+18/clik_+18 (4).mp4' },
        { name: 'Clik +18 5', url: 'videos/cliks_+18/clik_+18 (5).mp4' },
        { name: 'Clik +18 6', url: 'videos/cliks_+18/clik_+18 (6).mp4' },
    ],
}; 